
#configuracion para el acceso a base de datos
spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3351/tarea1
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root_password
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
endpoints:
  userController:
    getUserByNif:  getUserByNif  
    insertUser:  insertUser  
    getUserByNameAndLastName: getUserByNameAndLastName
    updateUser: updateUser
    
